-- 여기는 관리자 영역
-- SELLFIT 데이터 만들 공간
DROP TABLESPACE sellfit
INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

CREATE TABLESPACE sellfit
DATAFILE 'C:/oraclexe/data/sellfit.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K;

CREATE USER sellfit IDENTIFIED BY sellfit
DEFAULT TABLESPACE sellfit;

GRANT DBA TO sellfit;